### ISSUE TITLE
the  training@eventstore.com is broken

### ISSUE THREAD

**Issue by simkimsia** [EventStore/training-introduction-dotnet#4]
i think u need to remove [training@eventstore.com](mailto:training@eventstore.com) from your readme.md

i tried emailing and get this

![image](https://user-images.githubusercontent.com/245021/165748550-c2c32713-4ea7-4a5a-8e6b-8c32cb774ec3.png)

**Comment by oskardudycz** [comment]
Thanks for the finding, indeed it wasn't working, we fixed it, could you try again? I will close the issue, but if it's still not working for you, feel free to send us feedback.
