### ISSUE TITLE
the 4th step in the readme, can you give more precise substeps?

### ISSUE THREAD

**Issue by simkimsia** [EventStore/training-introduction-dotnet#5]
![image](https://user-images.githubusercontent.com/245021/165749341-35436dd5-6366-4d79-986d-da5c3f2aa602.png)
I'm using mac preview vs studio released in 2022 April.

your 4th step in the readme is run all the tests.

Can you advise on the more precise steps?

**Comment by oskardudycz** [comment]
You can run tests using the .NET command line:
```
dotnet test
```

On how to run tests in Visual Studio for Mac, check its documentation, e.g. https://docs.microsoft.com/en-us/visualstudio/mac/testing?view=vsmac-2019#running-tests.


I updated README instructions in Pull Request: https://github.com/EventStore/training-introduction-dotnet/pull/6.
